language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=NEURON

install: 
    - pip install git+https://github.com/borismarin/osb-model-validation.git

script:
    - omv all
    
    
    

